# Generated by Django 5.2.6 on 2025-09-12 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_post_newcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
